development:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_development
  pool: 5
  

test:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_test
  pool: 5
  

production:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_production
  pool: 5
  
