# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6a8dc8d5394273ad6ebdc166c440fc34a2adcd756e7844f52ebb2a917d02c06d700eecbc6033adb8a23382e24898caf3b3e7a96fb84ac5a36a14aa727684879

test:
  secret_key_base: 8a75a35a8bed06c9bfe93674fcbecae36f9796ce7787e0a32fbc486d06f8ac99edcaf4540c92bcbf7ebdc947800653c3c01fd0749f94e0ffa7a7f6d9147d947d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
